.TH  
.SH INSTALLATION TYPE OPTIONS
.TP
\fB \-\-full-suite (DEFAULT)\fP
The full suite installation will install every single package and application highlighted in the README.md.
.TP
\fB \-\-uninstall-full-suite\fP
Will remove/uninstall every single package and application highlighted in the README.md.
.SH INSTALLATION MODE OPTIONS (None enabled by default)
.TP
\fB \-\-fast-mode\fP
Attempts to speed things up a bit by running multiple installs as background processes. This will cause the output of this script to become reader UNfriendly during the installation process.